# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hitch < Formula
  desc "Git workflow manager for multi-environment development teams"
  homepage "https://github.com/DoomedRamen/hitch"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DoomedRamen/hitch/releases/download/v0.2.2/hitch_0.2.2_darwin_amd64.tar.gz"
      sha256 "ca16449d204d45babe2448c6cc18633c53c136f5be27d1dbb10368b9d216b883"

      def install
        bin.install "hitch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DoomedRamen/hitch/releases/download/v0.2.2/hitch_0.2.2_darwin_arm64.tar.gz"
      sha256 "b5c9307d40b11d31e7aa8c0e8f7da84dbc4f50313df24bd9147da71d8feada0a"

      def install
        bin.install "hitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoomedRamen/hitch/releases/download/v0.2.2/hitch_0.2.2_linux_amd64.tar.gz"
      sha256 "d48f6f8a6f14be8264dbee452ccd77d8521974819c0a0fb96ced9c9b1e5a69c1"
      def install
        bin.install "hitch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoomedRamen/hitch/releases/download/v0.2.2/hitch_0.2.2_linux_arm64.tar.gz"
      sha256 "3a66e658be007a8ffed02c5894040f5cd69202afaf3b3a4bf6e2891fa88188f4"
      def install
        bin.install "hitch"
      end
    end
  end

  test do
    system "#{bin}/hitch", "--version"
  end
end
